name: road_wave_fm_ui
description: Front-end interface to the NodeJS road-wave-fm-api
publish_to: 'none'
version: 0.9.0+2
homepage: https://github.com/LinkedMink/road_wave_fm_ui
repository: https://github.com/LinkedMink/road_wave_fm_ui
issue_tracker: https://github.com/LinkedMink/road_wave_fm_ui/issues
documentation: https://github.com/LinkedMink/road_wave_fm_ui
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.7.1
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  package_info_plus: ^1.3.0
  provider: ^6.0.1
  shared_preferences: ^2.0.9
  url_launcher: ^6.0.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# TODO
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
