name: Build main
concurrency: 
  group: build-main
  cancel-in-progress: true
on:
  push:
    branches:
    - main

jobs:
  build:
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/build-android.yml@main
    with:
      environmentName: develop
    secrets:
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_STORE_DATA: ${{ secrets.SIGNING_STORE_DATA }}
