name: Build
concurrency: 
  group: main-build
  cancel-in-progress: true
on:
  push:
    branches:
    - main
jobs:
  lint-test:
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/lint-test.yml@main
  build:
    environment: develop
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/build-android.yml@main
