name: Build Android
on:
  workflow_call:
    inputs:
      environmentName:
        description: 'Environment Name'
        default: develop
        required: false
        type: string
      outputBundles:
        description: 'Build app bundle and fat APK for store distribution'
        default: false
        type: boolean
    secrets:
      GOOGLE_MAPS_API_KEY:
        required: true
      SIGNING_STORE_PASSWORD:
        required: true
      SIGNING_KEY_ALIAS:
        required: true
      SIGNING_STORE_DATA:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environmentName }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Write publish-keystore.p12
      id: write_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'publish-keystore.p12'
        encodedString: ${{ secrets.SIGNING_STORE_DATA }}
    - name: Write build.properties
      run: |
        cat << EOF >> android/build.properties
        google.mapsApiKey=${{ secrets.GOOGLE_MAPS_API_KEY }}
        keys.storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}
        keys.storeFile=${{ steps.write_keystore.outputs.filePath }}
        keys.keyPassword=${{ secrets.SIGNING_STORE_PASSWORD }}
        keys.keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}
        EOF
    - name: Java Setup
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Flutter Setup
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.x'
        channel: 'beta'
    - name: Package Install
      run: flutter pub get
    - name: Build APK by ABI
      run: flutter build apk --no-pub --split-per-abi -v
    # - name: Build Fat APK
    #   if: ${{ inputs.outputBundles }}
    #   run: flutter build apk --no-pub -v
    - name: Build App Bundle
      if: ${{ inputs.outputBundles }}
      run: flutter build appbundle --no-pub -v
    - name: Upload Packages
      uses: actions/upload-artifact@v2
      with:
        name: app-packages
        path: build/app/deployed/
