name: Build
concurrency: 
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  lint-test:
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/lint-test.yml@main
  build:
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/build-android.yml@main
