name: Develop
on:
  push:
    branches:
      - main
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - feature/*
      - hotfix/*
jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.x'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter analyze --no-pub 
    - run: flutter test --reporter expanded --coverage
    - run: flutter build apk
