name: Lint and Test Dev
concurrency: 
  group: lint-test-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
    - feature/*
    - fix/*

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Java Setup
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        # cache: 'gradle'
    - name: Flutter Setup
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.x'
        channel: 'stable'
    - name: Package Install
      run: flutter pub get
    - name: Lint App
      run: flutter analyze --no-pub 
    - name: Test App
      run: flutter test --no-pub --reporter expanded --coverage
