name: Publish
concurrency: 
  group: publish
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'Environment Name'     
        required: false
        default: develop
jobs:
  build:
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/build-android.yml@main
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
  publish:
    needs: [build]
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/publish-android.yml@main
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
