# TODO
name: Publish
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - name: Download APKs
      uses: actions/download-artifact@master
      with:
        name: release.apks
    - name: Download App Bundle
      uses: actions/download-artifact@master
      with:
        name: release.aab
    - name: Publish to Play Store internal test track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: net.linkedmink.road_wave_fm_ui
        releaseFile: app-release.aab
        track: internal
        userFraction: 0.50
        mappingFile: mapping.txt
