name: Publish
concurrency: 
  group: publish
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Name'
        type: environment
        required: true
        default: develop
      uploadToTag:
        description: 'Upload built packages to Github tag'
        default: ''
        required: false
      stagedTrack:
        description: 'The staged release track in the play store to deploy to'
        default: internal
        required: true
        type: choice
        options:
        - internal
        - alpha
        - open
        # - production
jobs:
  build:
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/build-android.yml@main
    with:
      environmentName: ${{ github.event.inputs.environment }}
      outputBundles: true
    secrets:
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_STORE_DATA: ${{ secrets.SIGNING_STORE_DATA }}
  publish:
    needs: [build]
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/publish-android.yml@main
    with:
      environmentName: ${{ github.event.inputs.environment }}
      uploadToTag: ${{ github.event.inputs.uploadToTag }}
      stagedTrack: ${{ github.event.inputs.stagedTrack }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
