name: Publish
on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'Environment Name'     
        required: true
        default: develop
jobs:
  build:
    concurrency: 
      group: ${{ github.event.inputs.environmentName }}-publish
      cancel-in-progress: true
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/build-android.yml@main
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
  publish:
    needs: [build]
    uses: LinkedMink/road_wave_fm_ui/.github/workflows/publish-android.yml@main
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
