name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.x'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build appbundle
    # TODO
